### ISSUE TITLE
Normalization of HI-C matrix

### ISSUE THREAD

**Issue by Andi964** [SchulzLab/STARE#5]
Hello,

Can your method deal with e.g. VC-Normalized contact data or only with KR normalized data?
This would be relevant, since sometimes KR does not converge for specific chromosomes if data is sparse.

Best,
Andreas

**Comment by DennisHeck** [comment]
Hello!
In theory any normalization should work, as long as the contact frequencies for all candidate enhancers around a gene are comparable. But we didn't test any other method than KR yet for the CRISPRi-validation data. I wouldn't expect it to make much of a difference.
Best,
Dennis
