### ISSUE TITLE
Possible minor bugs in runTestCases.sh

### ISSUE THREAD

**Issue by MattQIMR** [SchulzLab/STARE#8]
There seems to be minor bugs in your runTestCases.sh.

> 
TestV16: ABC 500kb - Multiple Signal Columns - transfac PSCM file with automatic base content - Binary output
Preprocessing region file
Transforming transfac-PSCMs to PSEMs
Starting TRAP
0s TRAP
ABC-scoring region-gene interactions
Reading annotation and intersecting peaks
0s ABCpp: intersected genes and peaks
21 mapped to chr21_contacts.txt.gz
Fit for pseudocount not possible, proceeding without pseudocounts.
6ms; 21 contact matrix read
2ms; 21 processed and written
Compressing files
65ms compression
0s ABCpp in total
Generating TF-Gene scores
TRAP file read
Get the gene-region mapping from the ABC-scoring file(s)
Fetch affinity scalings out of the region file.
affinities fetched
Summarize the region affinities on gene level.
0ms;  Scores processed
Compressing output
7ms;  Compression
0s TF-Gene Scores
Congratulations it worked!

TestV17: separate ABC scoring - Multiple Signal Columns - average TSS
Reading annotation and intersecting peaks
ERROR Can't open the output path, please check carefully:
/mnt/lustre/working/lab_tracyo/mattheBa/Packages/Stare/Output//Test_V17/Test_V17_ABCpp_Temp_GeneWindow.bed
find: ‘/mnt/lustre/working/lab_tracyo/mattheBa/Packages/Stare/Output//Test_V17’: No such file or directory
ls: cannot access /mnt/lustre/working/lab_tracyo/mattheBa/Packages/Stare/Output//Test_V17/*: No such file or directory
ERROR: the number of files does not agree: /mnt/lustre/working/lab_tracyo/mattheBa/Packages/Stare/Output//Test_V17 /mnt/lustre/working/lab_tracyo/mattheBa/Packages/Stare/Test//Test_Controls/Test_V17

TestV18: separate ABC scoring - Use contact estimate - average TSS
Reading annotation and intersecting peaks
ERROR Can't open the output path, please check carefully:
/mnt/lustre/working/lab_tracyo/mattheBa/Packages/Stare/Output//Test_V18/Test_V18_ABCpp_Temp_GeneWindow.bed
find: ‘/mnt/lustre/working/lab_tracyo/mattheBa/Packages/Stare/Output//Test_V18’: No such file or directory
ls: cannot access /mnt/lustre/working/lab_tracyo/mattheBa/Packages/Stare/Output//Test_V18/*: No such file or directory
ERROR: the number of files does not agree: /mnt/lustre/working/lab_tracyo/mattheBa/Packages/Stare/Output//Test_V18 /mnt/lustre/working/lab_tracyo/mattheBa/Packages/Stare/Test//Test_Controls/Test_V18

TestV19: Windows 3kb - Promoter windows instead of bed-file
No bed-file provided, will run on promoter windows
Preprocessing region file
Writing promoter windows
Feature (1:98499-101500) beyond the length of 1 size (96000 bp).  Skipping.
Transforming transfac-PSCMs to PSEMs
Starting TRAP
1s TRAP
Generating TF-Gene scores
TRAP file read
affinities fetched
Summarize the region affinities on gene level.
1ms;  Scores processed
Compressing output
10ms;  Compression
0s TF-Gene Scores
Congratulations it  worked!
<
For Tests 12, 13, 14, 17 & 18 it tries to create a directory in the -i ./Test/ Directory but these already exists, it then tries saving to the -o ./output/Test_X directory which doesn't exist and then can't load from ./output/Test_X.

I believe in this case it's supposed to be creating  ./output/Test_X. I fixed it on my end by replacing
mkdir "$test_dir"/Test_V12
mkdir "$test_dir"/Test_V13
mkdir "$test_dir"/Test_V14
mkdir "$test_dir"/Test_V17
mkdir "$test_dir"/Test_V18
with
mkdir "$output"/Test_V12
mkdir "$output"/Test_V13
mkdir "$output"/Test_V14
mkdir "$output"/Test_V17
mkdir "$output"/Test_V18

**Comment by DennisHeck** [comment]
Thanks a lot for pointing that out and even give the solution to it! You're right, the mkdir had the wrong path. I pushed the correct version, and it will be included in the next release. 
Best wishes,
Dennis
