### ISSUE TITLE
Error: too many arguments

### ISSUE THREAD

**Issue by raquelsanzmar** [SchulzLab/STARE#9]
Hi,

I was trying your tool and I managed to get the output, but I always get this message in the end:
"Error: too many arguments"
However, I get the expected output and it seems that everything is working fine. I just wanted to make sure whether there is something that I am missing.

Thank you very much in advance! This is very helpful :)
 
Raquel

**Comment by SchulzLab** [comment]
Hi Raquel,
could you provide some example program call and with which data you get the error? Otherwise it is hard to comment whether your result would be expected.

Thanks,
Marcel

**Comment by raquelsanzmar** [comment]
Hi Marcel,
Thanks a lot for your answer.
This is how I call it:  `STARE_ABCpp -b $bed_file -n 4-6 -a $gene_annotation -o Output`

- `$bed_file` refers to a bed file with the ATAC peaks and the counts for 3 different columns
- `$gene_annotation` is a Gencode gtf-format file

When I run it, I get this message:
Reading annotation and intersecting peaks
31s ABCpp: intersected genes and peaks
763ms; 1 processed and written
569ms; 2 processed and written
478ms; 3 processed and written
304ms; 4 processed and written
379ms; 5 processed and written
394ms; 6 processed and written
376ms; 7 processed and written
312ms; 8 processed and written
312ms; 9 processed and written
326ms; 10 processed and written
492ms; 11 processed and written
448ms; 12 processed and written
159ms; 13 processed and written
331ms; 14 processed and written
314ms; 15 processed and written
353ms; 16 processed and written
535ms; 17 processed and written
162ms; 18 processed and written
476ms; 19 processed and written
184ms; 20 processed and written
110ms; 21 processed and written
203ms; 22 processed and written
243ms; X processed and written
58ms; Y processed and written
Compressing files
6861ms compression
46s ABCpp in total
**Error: too many arguments.**

However, I do get the Output_ABCpp_scoredInteractions and Output_GeneInfo txt.gz files for each of the columns

Thanks a lot again!

**Comment by DennisHeck** [comment]
Dear Raquel,

Happy to hear that you find it useful! 
I couldn't reproduce your error when using the same flags. The last message from the STARE_ABCpp function itself is the reported runtime, in your case '46s ABCpp in total'. To me it looks like a message from the shell, but I'm not sure what causes it. As long as the output files are written and compressed, I think it should be fine.

Best wishes,
Dennis

**Comment by raquelsanzmar** [comment]
Hi Dennis,

Thanks a lot! You are right, now I've been able to fix it and it was not coming from your program :)
Again, thank you very much, this is very helpful!!

Best,
Raquel
